#!/bin/bash

# Where the magic happens.
export DOTFILES=~/dotfiles

# Add binaries into the path
[[ -d $HOME/.bin ]] && PATH=$HOME/.bin:$PATH
PATH=$DOTFILES/bin:$PATH
PATH=$HOME/.local/bin:$PATH
PATH=$HOME/Library/Python/2.7/bin:$PATH
export PATH

# Source all files in "source"
function src() {
  for function in ~/.bash/source/*; do
    source $function
  done
}

# Run dotfiles script, then source.
function dotfiles() {
  rcup && ~/.bin/dotfiles "$@" && src
}

src

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

export HISTTIMEFORMAT="%d/%m/%y %T - "



export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


function resetsound() {
  sudo kill -9 `ps ax|grep 'coreaudio[a-z]' | awk '{print $1}'`
  sudo killall coreaudiod
}


alias xhr='curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Requested-With: XMLHttpRequest"'



function nxttag() {
   git tag | ruby -e 'puts ARGF.read.split.map {|l| l.split(".").map(&:to_i) }.sort(&:<=>).last.tap{|l|l[-1] +=1}.join(".")'
}

