#!/bin/bash

# Where the magic happens.
export DOTFILES=~/dotfiles

# Add binaries into the path
[[ -d $HOME/.bin ]] && PATH=$HOME/.bin:$PATH
PATH=$DOTFILES/bin:$PATH
export PATH

# Source all files in "source"
function src() {
  for function in ~/.bash/source/*; do
    source $function
  done
}

# Run dotfiles script, then source.
function dotfiles() {
  rcup && ~/.bin/dotfiles "$@" && src
}

src

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# added by travis gem
[ -f /Users/manuel.albarran/.travis/travis.sh ] && source /Users/manuel.albarran/.travis/travis.sh
