# Where the magic happens.
export DOTFILES=~/dotfiles

# Add binaries into the path
[[ -d $HOME/.bin ]] && PATH=$HOME/.bin:$PATH
PATH=$DOTFILES/bin:$PATH
export PATH

# Source all files in "source"
function src() {
  local file
  if [[ "$1" ]]; then
    source "$DOTFILES/source/$1.sh"
  else
    for file in $DOTFILES/source/*; do
      source "$file"
    done
  fi
}

function dropbox_src() {
  local file
  if [[ "$1" ]]; then
    source "$DOTFILES/source/$1.sh"
  else
    for file in $HOME/Dropbox/dotfiles/source/*; do
      source "$file"
    done
  fi
}

# Run dotfiles script, then source.
# function dotfiles() {
#   $DOTFILES/bin/dotfiles "$@" && src
# }

src
dropbox_src

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh
