if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

export PATH="$HOME/.cargo/bin:/usr/local/opt/curl/bin:$PATH"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/manu/Downloads/google-cloud-sdk/path.bash.inc' ]; then source '/Users/manu/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/manu/Downloads/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/manu/Downloads/google-cloud-sdk/completion.bash.inc'; fi
