#!/bin/sh

local_hook="$HOME"/.git_template.local/hooks/pre-commit

if [ -f "$local_hook" ]; then
  . "$local_hook"
fi

read -r -d '' fail_words <<- EOM
  # debugger
  # byebug
  # binding.pry
  show me the page
  # console.log
  >>>>>>
  <<<<<<
  # ======
EOM

while read -r line
do
  (git diff --cached | grep -q "$line") && echo "Fail words found: '$line' Fix your commit damn it..." && exit 1
done <<< "$fail_words"
exit 0
