source "https://rubygems.org"

gem "pry", group: %w(development test)

group "test" do
  gem "rspec"
  gem "rspec-its"
  gem "simplecov", require: false
end

group "development" do
  gem "guard-rspec", require: false
  gem "guard-rubocop", require: false
end
